### Numpy 기초
- 수치 해석, 수학적 계산을 목적으로 한 라이브러리, 수치해석 최적화

#### Numpy 설치
```shell
!pip install [update] numpy
```

In [3]:
!pip install update numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------------------------- ------------ 41.0/60.9 kB 991.0 kB/s eta 0:00:01
     ---------------------------------------- 60.9/60.9 kB 1.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/16.3 MB ? eta -:--:--
   - -------------------------------------- 0.4/16.3 MB 12.9 MB/s eta 0:00:02
   -- ------------------------------------- 1.0/16.3 MB 12.2 MB/s eta 0:00:02
   --- ------------------------------------ 1.4/16.3 MB 11.4 MB/s eta 0:00:02
   ---- ----------------------------------- 2.0/16.3 MB 11.5 MB/s eta 0:00:02
   ------ --------------------------------- 2.5/16.3 MB 11.4 MB/s eta 0:00:02
   ------- -------------------------------- 3.0/16.3 MB 11.3 MB/s eta 0:00:02
   -------- ------------------------------- 3.6/16.3 MB 11.4 MB/s eta 0:00:02
   ---------- ----------------------------- 4.1/16.3 MB 11.4 MB/s eta 0:00:02
   ----------- ---------------------------- 4.7/16.3 MB 11.5 MB/s eta 0:00


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np # 보통 np로 줄여씀

In [9]:
lst = [1,2,3,4]

In [23]:
# 배열 생성
arr1 = np.array(lst) # == np.array([1,2,3,4])
arr1 # numpy 배열

array([1, 2, 3, 4])

In [22]:
# 배열의 구조
arr1.shape # 1차원 배열, 크기 4

(4,)

In [16]:
# 2차원 배열
arr2 = np.array([[1,2,3,4,],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.shape  # 2차원 배열, 2행 4열

(2, 4)

In [19]:
arr3 = np.array([[1,2,3,4]])
arr3

array([[1, 2, 3, 4]])

In [24]:
arr3.shape

(1, 4)

In [27]:
arr4 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])
arr4.shape

(2, 4, 4)

In [29]:
# 넘파이 데이터 타입 확인
arr3.dtype

dtype('int64')

- 넘파이 자료형
    - 부호 정수 : int8, int16, int32, int64
    - 무부호 정수 : uint8, uint16, uint32, uint64
    - 실수 : float8, float16, float32, float64
    - 복소수 : complex8, complex16, complex32, complex64
    - 문자열 : string_
    - 불린 : bool
    - 유니코드 : unicode_
    - 파이썬오브젝트 : object

- 넘파이 배열 정의

In [30]:
# 1차원 요소가 10개가 모두 0인 배열 초기화
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
# 2차원 2행 4열 모두가 0인 배열 초기화
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
# 1차원 요소가 10개가 모두 1인 배열 초기화
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
# 2차원 2행 4열 모두가 1인 배열 초기화
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
# 3부터 1씩 증가, 9가 마지막인 배열 초기화
arr1 = np.arange(3, 10)
arr2 = np.arange(3, 10, 2)
print(arr1, arr2)

[3 4 5 6 7 8 9] [3 5 7 9]


- 사용하는 이유

In [53]:
## 대량리스트 생성
pyList = list(range(10_000_000))
npList = np.arange(10_000_000)

In [54]:
len(pyList)

10000000

In [55]:
npList.shape

(10000000,)

In [56]:
## 파이썬 리스트 계산 처리 시간
%timeit for _ in range (10) : pyList2 = pyList * 2

1.95 s ± 64.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [58]:
## 넘파이 배열 계산처리 시간
%timeit for _ in range(10) : npList2 = npList * 2

250 ms ± 10.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


- 넘파이로 수치 계산을 하면 시간을 절약!